import { useEffect, useRef, useState } from "react";
import { CountUp, Spinner } from "../components/ui";
import { endpoints, googleStartUrl, useApi } from "../lib/api";
import { useAuth } from "../lib/auth";
import { money, number } from "../lib/format";
import "./auth.css";

/* ==========================================================================
   Sign in and sign up. One split layout: the argument on the left, the form on
   the right, and the same warm palette as the rest of the product.
   ========================================================================== */

function Panel({ navigate, summary, meta }) {
  const facts = [
    { label: "Book under management", value: money(summary?.book_principal ?? 0) },
    { label: "Accounts needing attention", value: number(summary?.needs_attention?.accounts ?? 0) },
    { label: "Recoverable this cycle", value: money(summary?.expected_recovery_available ?? 0) },
  ];

  return (
    <aside className="auth__panel">
      <div className="auth__glow" aria-hidden="true">
        <span className="auth__blob auth__blob--a" />
        <span className="auth__blob auth__blob--b" />
      </div>
      <div className="auth__grid-lines" aria-hidden="true" />

      <a
        className="brand brand--on-dark"
        href="/"
        onClick={(event) => {
          event.preventDefault();
          navigate("/");
        }}
      >
        <span className="brand__mark" aria-hidden="true">
          <svg viewBox="0 0 32 32" width="26" height="26">
            <rect width="32" height="32" rx="8" fill="var(--clay)" />
            <path d="M7 24V8h3.1l7.4 10.2V8H21v16h-3.1L10.5 13.8V24H7z" fill="#fff" />
          </svg>
        </span>
        <span className="brand__text">
          <strong>Northline</strong>
          <small>Credit &amp; Recovery</small>
        </span>
      </a>

      <div className="auth__pitch">
        <h2 className="display auth__pitch-title">
          The queue your team
          <br />
          works before lunch.
        </h2>
        <p className="auth__pitch-sub">
          Every account ranked by the money at stake, with the playbook to run and the outcome
          recorded.
        </p>
      </div>

      <dl className="auth__facts">
        {facts.map((fact, index) => (
          <div
            className="auth__fact enter"
            key={fact.label}
            style={{ "--enter-delay": `${140 + index * 90}ms` }}
          >
            <dt>{fact.label}</dt>
            <dd>{fact.value}</dd>
          </div>
        ))}
      </dl>

      <p className="auth__disclosure">
        {meta?.synthetic
          ? "Demonstration portfolio generated by Northline. Not real borrower data."
          : "Live portfolio."}
      </p>
    </aside>
  );
}

function Field({ label, type = "text", value, onChange, placeholder, autoComplete, hint, children }) {
  const [reveal, setReveal] = useState(false);
  const isPassword = type === "password";
  return (
    <label className="field">
      <span className="field__label">{label}</span>
      <span className="field__control">
        <input
          type={isPassword && reveal ? "text" : type}
          value={value}
          placeholder={placeholder}
          autoComplete={autoComplete}
          onChange={(event) => onChange(event.target.value)}
        />
        {isPassword ? (
          <button
            type="button"
            className="field__reveal"
            onClick={() => setReveal((state) => !state)}
            aria-label={reveal ? "Hide password" : "Show password"}
          >
            {reveal ? "Hide" : "Show"}
          </button>
        ) : null}
        {children}
      </span>
      {hint ? <span className="field__hint">{hint}</span> : null}
    </label>
  );
}

function Submit({ busy, children }) {
  return (
    <button className="btn btn--signal btn--lg auth__submit" type="submit" disabled={busy}>
      {busy ? <span className="spin" aria-hidden="true">◐</span> : null}
      {busy ? "One moment…" : children}
    </button>
  );
}

/** The official four-colour Google mark. */
function GoogleMark({ size = 17 }) {
  return (
    <svg width={size} height={size} viewBox="0 0 48 48" aria-hidden="true">
      <path
        fill="#EA4335"
        d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"
      />
      <path
        fill="#4285F4"
        d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"
      />
      <path
        fill="#FBBC05"
        d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"
      />
      <path
        fill="#34A853"
        d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"
      />
    </svg>
  );
}

/**
 * "Continue with Google", or — for whoever is running the server — a note saying
 * why it is missing. The backend decides, so a button that cannot work is never
 * shown to a real visitor.
 */
function GoogleSignIn({ providers, next = "/app" }) {
  if (providers?.google) {
    return (
      <>
        <button
          className="btn btn--google btn--lg"
          type="button"
          onClick={() => {
            // A full-page navigation: the browser has to visit Google itself.
            window.location.href = googleStartUrl(next);
          }}
        >
          <GoogleMark />
          Continue with Google
        </button>
        <div className="auth__divider" role="separator" aria-orientation="horizontal">
          <span>or</span>
        </div>
      </>
    );
  }

  if (!import.meta.env?.DEV) return null;

  return (
    <p className="auth__provider-note">
      Google sign-in is not configured on this server. Add{" "}
      <span className="mono">GOOGLE_CLIENT_ID</span> and{" "}
      <span className="mono">GOOGLE_CLIENT_SECRET</span> to{" "}
      <span className="mono">backend/.env</span>, then restart the API.
    </p>
  );
}

/** Reads ?error= that the OAuth callback may have appended. */
function useUrlError() {
  return useState(() => {
    if (typeof window === "undefined") return null;
    return new URLSearchParams(window.location.search).get("error") || null;
  })[0];
}

export function SignInPage({ navigate }) {
  const { signIn } = useAuth();
  const { data: summary } = useApi(endpoints.summary());
  const { data: meta } = useApi(endpoints.meta());
  const { data: demo } = useApi(endpoints.demo());
  const { data: providers } = useApi(endpoints.providers());

  const urlError = useUrlError();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    if (demo?.accounts?.length && !email) {
      setEmail(demo.accounts[0].email);
      setPassword(demo.password);
    }
  }, [demo, email]);

  async function submit(event) {
    event.preventDefault();
    setBusy(true);
    setError(null);
    try {
      await signIn(email.trim(), password);
      navigate("/app");
    } catch (err) {
      setError(err.message);
      setBusy(false);
    }
  }

  return (
    <div className="auth">
      <Panel navigate={navigate} summary={summary} meta={meta} />

      <main className="auth__form-side">
        <form className="auth__form enter" onSubmit={submit}>
          <header className="auth__form-head">
            <span className="eyebrow eyebrow--signal">Welcome back</span>
            <h1 className="auth__title">Sign in</h1>
            <p className="note">Pick up the queue where your team left it.</p>
          </header>

          {error || urlError ? (
            <p className="auth__error" role="alert">
              {error || urlError}
            </p>
          ) : null}

          <GoogleSignIn providers={providers} next="/app" />

          <Field
            label="Work email"
            type="email"
            value={email}
            onChange={setEmail}
            placeholder="you@lender.ng"
            autoComplete="email"
          />
          <Field
            label="Password"
            type="password"
            value={password}
            onChange={setPassword}
            placeholder="••••••••"
            autoComplete="current-password"
          />

          <Submit busy={busy}>Sign in</Submit>

          {demo?.accounts?.length ? (
            <div className="auth__demo">
              <span className="eyebrow">Or step into a seeded role</span>
              <div className="auth__demo-list">
                {demo.accounts.map((account) => (
                  <button
                    key={account.email}
                    type="button"
                    className={`auth__demo-chip${email === account.email ? " is-active" : ""}`}
                    onClick={() => {
                      setEmail(account.email);
                      setPassword(demo.password);
                    }}
                  >
                    <span className="auth__demo-name">{account.name}</span>
                    <span className="auth__demo-role">{account.role_label}</span>
                  </button>
                ))}
              </div>
              <p className="note">
                Shared demo password <span className="mono">{demo.password}</span>
              </p>
            </div>
          ) : null}

          <p className="auth__switch">
            No account yet?{" "}
            <button type="button" onClick={() => navigate("/sign-up")}>
              Create a workspace
            </button>
          </p>
        </form>
      </main>
    </div>
  );
}

export function SignUpPage({ navigate }) {
  const { signUp } = useAuth();
  const { data: summary } = useApi(endpoints.summary());
  const { data: meta } = useApi(endpoints.meta());
  const { data: roles } = useApi(endpoints.roles());
  const { data: providers } = useApi(endpoints.providers());

  const [form, setForm] = useState({ orgName: "", name: "", email: "", password: "" });
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState(null);

  const update = (key) => (value) => setForm((prev) => ({ ...prev, [key]: value }));

  async function submit(event) {
    event.preventDefault();
    setBusy(true);
    setError(null);
    try {
      await signUp({
        org_name: form.orgName.trim(),
        name: form.name.trim(),
        email: form.email.trim(),
        password: form.password,
      });
      navigate("/app");
    } catch (err) {
      setError(err.message);
      setBusy(false);
    }
  }

  return (
    <div className="auth">
      <Panel navigate={navigate} summary={summary} meta={meta} />

      <main className="auth__form-side">
        <form className="auth__form enter" onSubmit={submit}>
          <header className="auth__form-head">
            <span className="eyebrow eyebrow--signal">New workspace</span>
            <h1 className="auth__title">Create your org</h1>
            <p className="note">You will be its administrator. Add the rest of the team after.</p>
          </header>

          {error ? (
            <p className="auth__error" role="alert">
              {error}
            </p>
          ) : null}

          <GoogleSignIn providers={providers} next="/app" />

          <Field
            label="Lending business"
            value={form.orgName}
            onChange={update("orgName")}
            placeholder="Adeola Capital Ltd"
            autoComplete="organization"
          />
          <div className="auth__row">
            <Field
              label="Your name"
              value={form.name}
              onChange={update("name")}
              placeholder="Ade Balogun"
              autoComplete="name"
            />
            <Field
              label="Work email"
              type="email"
              value={form.email}
              onChange={update("email")}
              placeholder="you@lender.ng"
              autoComplete="email"
            />
          </div>
          <Field
            label="Password"
            type="password"
            value={form.password}
            onChange={update("password")}
            placeholder="At least 8 characters"
            autoComplete="new-password"
            hint="Eight characters or more. Long beats complicated."
          />

          <Submit busy={busy}>Create workspace</Submit>

          <div className="auth__roles">
            <span className="eyebrow">Roles you can hand out</span>
            <ul>
              {(roles?.roles ?? []).map((role) => (
                <li key={role.code}>
                  <span className="auth__role-name">{role.label}</span>
                  <span className="auth__role-desc">{role.description}</span>
                </li>
              ))}
            </ul>
          </div>

          <p className="auth__switch">
            Already have a workspace?{" "}
            <button type="button" onClick={() => navigate("/sign-in")}>
              Sign in
            </button>
          </p>
        </form>
      </main>
    </div>
  );
}

/**
 * Where Google returns the browser.
 *
 * The URL carries a one-time code, never the session token. We trade it here for
 * a real session in a POST body, so the credential stays out of browser history,
 * referrer headers and server access logs.
 */
export function AuthCallbackPage({ navigate }) {
  const { completeGoogle } = useAuth();
  const { data: summary } = useApi(endpoints.summary());
  const { data: meta } = useApi(endpoints.meta());
  const [state, setState] = useState({ status: "working", message: "Finishing sign-in…" });
  const started = useRef(false);

  useEffect(() => {
    // React runs effects twice in development; the code is single-use, so it must
    // only be redeemed once.
    if (started.current) return;
    started.current = true;

    const params = new URLSearchParams(window.location.search);
    const code = params.get("code");
    const next = params.get("next");
    const error = params.get("error");

    if (error) {
      setState({ status: "error", message: error });
      return;
    }
    if (!code) {
      setState({ status: "error", message: "That sign-in link was incomplete." });
      return;
    }

    completeGoogle(code)
      .then(() => {
        // Only ever continue to a path on this site.
        const target = next && next.startsWith("/") && !next.startsWith("//") ? next : "/app";
        navigate(target);
      })
      .catch((failure) => setState({ status: "error", message: failure.message }));
  }, [completeGoogle, navigate]);

  return (
    <div className="auth">
      <Panel navigate={navigate} summary={summary} meta={meta} />
      <main className="auth__form-side">
        <div className="auth__form enter">
          <header className="auth__form-head">
            <span className="eyebrow eyebrow--signal">Google sign-in</span>
            <h1 className="auth__title">
              {state.status === "working" ? "Almost there" : "That didn't work"}
            </h1>
          </header>

          {state.status === "working" ? (
            <div className="auth__working">
              <Spinner size={20} />
              <span className="note">{state.message}</span>
            </div>
          ) : (
            <>
              <p className="auth__error" role="alert">
                {state.message}
              </p>
              <button
                className="btn btn--signal btn--lg auth__submit"
                type="button"
                onClick={() => navigate("/sign-in")}
              >
                Back to sign in
              </button>
            </>
          )}
        </div>
      </main>
    </div>
  );
}
