"""Northline API.

Every figure returned here is computed from the seeded portfolio. The demo data is
synthetic and the API says so in ``/api/meta`` so the interface can label it
honestly rather than implying a real book.
"""

from __future__ import annotations

import csv
import io
import json
from datetime import date
from typing import Any

from fastapi import FastAPI, HTTPException, Query, Request, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, PlainTextResponse
from pydantic import BaseModel, Field

from . import analytics, auth, auth_api, config, env, operations, playbooks, priority, scoring
from .db import connect, create_schema, get_meta

app = FastAPI(
    title="Northline API",
    version="1.0.0",
    description="Credit & Recovery Intelligence — portfolio, triage and recovery operations.",
)


def allowed_origins() -> list[str]:
    """Origins allowed to call the API from a browser.

    Local development needs the dev server. A deployment that serves the built
    interface from the same origin as the API needs no entry at all; one that
    splits them sets ``ALLOWED_ORIGINS`` to a comma-separated list.
    """
    configured = env.get("ALLOWED_ORIGINS")
    if configured:
        return [origin.strip() for origin in configured.split(",") if origin.strip()]
    return ["http://127.0.0.1:5180", "http://localhost:5180"]


app.add_middleware(
    CORSMiddleware,
    allow_origins=allowed_origins(),
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(auth_api.router)

# Borrower-level records, the live queue and organisation data require a session.
# Aggregate portfolio reporting stays public: it is the marketing argument, and it
# exposes no individual borrower. That is the line a real product would draw.
PROTECTED_PREFIXES = ("/api/worklist", "/api/accounts")


@app.middleware("http")
async def gate_borrower_records(request: Request, call_next):
    path = request.url.path
    if request.method != "OPTIONS" and path.startswith(PROTECTED_PREFIXES):
        token = auth.bearer_token(request.headers.get("authorization"))
        user = None
        if token:
            connection = _connection()
            try:
                user = auth.user_for_token(connection, token)
            finally:
                connection.close()
        if user is None:
            return JSONResponse(
                {"detail": "Sign in to open borrower records."}, status_code=401
            )
        request.state.user = user
    return await call_next(request)


def _connection():
    connection = connect()
    create_schema(connection)
    return connection


@app.get("/api/health")
def health() -> dict[str, Any]:
    connection = _connection()
    try:
        accounts = connection.execute("SELECT COUNT(*) AS n FROM accounts").fetchone()["n"]
    finally:
        connection.close()
    return {"status": "healthy", "accounts": accounts}


@app.get("/api/meta")
def meta() -> dict[str, Any]:
    connection = _connection()
    try:
        return {
            "as_of": get_meta(connection, "as_of", config.AS_OF.isoformat()),
            "seed": get_meta(connection, "seed"),
            "generator": get_meta(connection, "generator"),
            "synthetic": get_meta(connection, "synthetic") == "true",
            "disclaimer": (
                "Demonstration portfolio generated by Northline. Not real borrower data. "
                "The risk index is a transparent weighted index, not a calibrated "
                "probability of default."
            ),
            "currency": config.CURRENCY,
            "currency_symbol": config.CURRENCY_SYMBOL,
            "officers": config.COLLECTIONS_OFFICERS,
            "relationship_managers": config.RELATIONSHIP_MANAGERS,
            "channels": [
                {
                    "code": code,
                    "label": code.replace("_", " "),
                    "cost": config.attempt_cost(code),
                    "direct_cost": config.CHANNEL_COST[code],
                    "officer_minutes": config.OFFICER_MINUTES[code],
                }
                for code in config.CHANNELS
            ],
            "dispositions": [
                {"code": code, "label": config.DISPOSITION_LABELS[code]}
                for code in config.DISPOSITIONS
            ],
            "bands": [
                {"index": band["index"], "code": band["code"], "label": band["label"]}
                for band in config.BANDS
            ],
            "playbooks": [
                {"code": playbook["code"], "name": playbook["name"], "owner": playbook["owner"]}
                for playbook in config.PLAYBOOKS
            ],
        }
    finally:
        connection.close()


@app.get("/api/portfolio/summary")
def portfolio_summary() -> dict[str, Any]:
    connection = _connection()
    try:
        return analytics.portfolio_summary(connection)
    finally:
        connection.close()


@app.get("/api/portfolio/par-trend")
def par_trend(months: int = Query(18, ge=3, le=36)) -> dict[str, Any]:
    connection = _connection()
    try:
        return {"series": analytics.par_trend(connection, months)}
    finally:
        connection.close()


@app.get("/api/portfolio/migration")
def migration(since: str = Query("2026-01-01")) -> dict[str, Any]:
    connection = _connection()
    try:
        return analytics.migration_matrix(connection, since)
    finally:
        connection.close()


@app.get("/api/portfolio/vintages")
def vintages(min_cohort: str = Query("2024-06")) -> dict[str, Any]:
    connection = _connection()
    try:
        return analytics.vintage_curves(connection, min_cohort)
    finally:
        connection.close()


@app.get("/api/portfolio/advance-warning")
def advance_warning() -> dict[str, Any]:
    connection = _connection()
    try:
        return analytics.advance_warning(connection)
    finally:
        connection.close()


@app.get("/api/portfolio/coverage")
def coverage() -> dict[str, Any]:
    connection = _connection()
    try:
        return analytics.monitoring_coverage(connection)
    finally:
        connection.close()


@app.get("/api/portfolio/featured-case")
def featured_case() -> dict[str, Any]:
    """An anonymised worked example, for the public page.

    Borrower identity is replaced by a sector and city description. A marketing page
    has no business showing a named company's distress, and gating borrower records
    behind a session would be pointless if the site leaked one on the way in.
    """
    connection = _connection()
    try:
        row = connection.execute(
            "SELECT s.code, s.label, s.headline, s.detected_at, s.lead_days, s.severity, "
            "       a.id AS account_id, a.product_name, a.product_code, a.outstanding_principal, "
            "       a.dpd, b.sector, b.city "
            "FROM signal_events s JOIN accounts a ON a.id = s.account_id "
            "JOIN borrowers b ON b.id = a.borrower_id "
            "WHERE s.code = 'inflow_decline' AND s.lead_days > 20 AND a.dpd > 0 "
            "ORDER BY s.lead_days DESC LIMIT 1"
        ).fetchone()
        if row is None:
            raise HTTPException(status_code=404, detail="No worked example available.")

        series = [
            dict(item)
            for item in connection.execute(
                "SELECT month, inflow, closing_balance FROM cashflow_months "
                "WHERE account_id = ? ORDER BY month",
                (row["account_id"],),
            ).fetchall()
        ]
        account = analytics.get_book_account(connection, row["account_id"])
        change = ((account or {}).get("cashflow") or {}).get("change_pct")

        return {
            "descriptor": f"A {row['sector'].lower()} business in {row['city']}",
            "sector": row["sector"],
            "city": row["city"],
            "product_name": row["product_name"],
            "product_code": row["product_code"],
            "outstanding_principal": row["outstanding_principal"],
            "days_past_due": row["dpd"],
            "lead_days": row["lead_days"],
            "change_pct": change,
            "signal": {
                "code": row["code"],
                "label": row["label"],
                "headline": row["headline"],
                "detected_at": row["detected_at"],
                "severity": row["severity"],
            },
            "cashflow": series,
        }
    finally:
        connection.close()


@app.get("/api/portfolio/ordering-demo")
def ordering_demo(budget: int = Query(25, ge=5, le=250)) -> dict[str, Any]:
    """The public ordering comparison.

    Same engine as the workspace, but account identity is replaced with a sector
    and city so a marketing page never names a borrower.
    """
    connection = _connection()
    try:
        result = analytics.worklist(connection, budget=budget)
        ranking = result["ranking"]

        def mask(rows: list[dict]) -> list[dict]:
            return [
                {
                    "label": f"{row['sector']} · {row['city']}",
                    "dpd": row["dpd"],
                    "band": row["band"],
                    "band_label": row["band_label"],
                    "expected_recovery": row["expected_recovery"],
                }
                for row in rows
            ]

        return {
            "budget": budget,
            "eligible": result["eligible"],
            "actionable_accounts": ranking["actionable_accounts"],
            "total_expected_recovery": ranking["total_expected_recovery"],
            "northline": ranking["northline"],
            "baseline_dpd_order": ranking["baseline_dpd_order"],
            "lift_vs_dpd_order": ranking["lift_vs_dpd_order"],
            "rows": mask(result["rows"]),
            "baseline_rows": mask(result["baseline_rows"]),
        }
    finally:
        connection.close()


@app.get("/api/worklist")
def worklist(
    budget: int | None = Query(None, ge=1, le=2000),
    officer: str | None = None,
    band: int | None = Query(None, ge=0, le=4),
    product: str | None = None,
    search: str | None = None,
) -> dict[str, Any]:
    connection = _connection()
    try:
        return analytics.worklist(
            connection, budget=budget, officer=officer, band=band, product=product, search=search
        )
    finally:
        connection.close()


@app.get("/api/accounts/{account_id}")
def account_detail(account_id: int) -> dict[str, Any]:
    connection = _connection()
    try:
        account = analytics.get_book_account(connection, account_id)
        if account is None:
            raise HTTPException(status_code=404, detail="Account not found")

        schedule = [
            dict(row)
            for row in connection.execute(
                "SELECT seq, due_date, amount_due, amount_paid, status FROM installments "
                "WHERE account_id = ? ORDER BY seq",
                (account_id,),
            ).fetchall()
        ]
        payments = [
            dict(row)
            for row in connection.execute(
                "SELECT paid_date, amount, channel, source FROM payments WHERE account_id = ? "
                "ORDER BY paid_date DESC LIMIT 40",
                (account_id,),
            ).fetchall()
        ]
        promises = [
            dict(row)
            for row in connection.execute(
                "SELECT id, made_at, promised_date, amount, status, resolved_at FROM promises "
                "WHERE account_id = ? ORDER BY made_at DESC",
                (account_id,),
            ).fetchall()
        ]
        actions = [
            dict(row)
            for row in connection.execute(
                "SELECT id, occurred_at, channel, disposition, officer, playbook_code, notes, "
                "cost, effect FROM actions WHERE account_id = ? ORDER BY occurred_at DESC LIMIT 40",
                (account_id,),
            ).fetchall()
        ]
        cashflow = [
            dict(row)
            for row in connection.execute(
                "SELECT month, inflow, outflow, closing_balance, pos_inflow, transfer_inflow, "
                "new_recurring_debits FROM cashflow_months WHERE account_id = ? ORDER BY month",
                (account_id,),
            ).fetchall()
        ]

        siblings = [
            {
                "id": row["id"],
                "ref": row["ref"],
                "product_name": row["product_name"],
                "outstanding_principal": row["outstanding_principal"],
                "dpd": row["dpd"],
                "status": row["status"],
            }
            for row in connection.execute(
                "SELECT id, ref, product_name, outstanding_principal, dpd, status FROM accounts "
                "WHERE borrower_id = ? AND id != ?",
                (account["borrower_id"], account_id),
            ).fetchall()
        ]

        return {
            "account": {
                key: value
                for key, value in account.items()
                if key not in ("signals", "actionable_signals", "cashflow")
            },
            "risk": account["risk"],
            "playbook": account["playbook"],
            "priority_value": account["priority_value"],
            "signals": account["signals"],
            "cashflow": account["cashflow"],
            "cashflow_series": cashflow,
            "schedule": schedule,
            "payments": payments,
            "promises": promises,
            "actions": actions,
            "siblings": siblings,
            "timeline": operations.account_timeline(connection, account_id),
        }
    finally:
        connection.close()


class ActionRequest(BaseModel):
    channel: str = Field(..., description="call, whatsapp, sms, email, field_visit, payment_link")
    disposition: str
    officer: str
    playbook_code: str | None = None
    notes: str = ""
    promised_date: str | None = None
    promised_amount: int | None = None


@app.post("/api/accounts/{account_id}/actions")
def log_action(account_id: int, request: ActionRequest) -> dict[str, Any]:
    connection = _connection()
    try:
        return operations.log_action(
            connection,
            account_id,
            channel=request.channel,
            disposition=request.disposition,
            officer=request.officer,
            playbook_code=request.playbook_code,
            notes=request.notes,
            promised_date=request.promised_date,
            promised_amount=request.promised_amount,
        )
    except KeyError as error:
        raise HTTPException(status_code=404, detail=str(error)) from error
    except ValueError as error:
        raise HTTPException(status_code=400, detail=str(error)) from error
    finally:
        connection.close()


class PromiseResolution(BaseModel):
    kept: bool
    settled_amount: int | None = None


@app.post("/api/accounts/{account_id}/promises/{promise_id}/resolve")
def resolve_promise(account_id: int, promise_id: int, body: PromiseResolution) -> dict[str, Any]:
    connection = _connection()
    try:
        return operations.resolve_promise(
            connection, account_id, promise_id, body.kept, body.settled_amount
        )
    except KeyError as error:
        raise HTTPException(status_code=404, detail=str(error)) from error
    except ValueError as error:
        raise HTTPException(status_code=400, detail=str(error)) from error
    finally:
        connection.close()


@app.get("/api/recovery/summary")
def recovery_summary() -> dict[str, Any]:
    connection = _connection()
    try:
        return {
            "ledger": analytics.roi_ledger(connection),
            "performance": analytics.recovery_performance(connection),
        }
    finally:
        connection.close()


@app.get("/api/playbooks")
def playbook_catalogue() -> dict[str, Any]:
    connection = _connection()
    try:
        performance = analytics.recovery_performance(connection)["by_playbook"]
        by_code = {row["code"]: row for row in performance}
        return {
            "playbooks": playbooks.catalogue(),
            "performance": by_code,
            "channels": [
                {"code": code, "cost": cost} for code, cost in config.CHANNEL_COST.items()
            ],
            "priority_thresholds": {
                "high": priority.PRIORITY_HIGH,
                "medium": priority.PRIORITY_MEDIUM,
            },
        }
    finally:
        connection.close()


@app.get("/api/alerts")
def alerts(limit: int = Query(60, ge=1, le=300)) -> dict[str, Any]:
    connection = _connection()
    try:
        return {"alerts": analytics.alert_feed(connection, limit)}
    finally:
        connection.close()


@app.get("/api/scoring/model-card")
def model_card() -> dict[str, Any]:
    return {
        "name": "Northline Risk Index v1",
        "type": "Transparent weighted index",
        "outputs": "0-100 index, band, component breakdown, plain-language reasons",
        "weights": scoring.WEIGHTS,
        "bands": [
            {"code": code, "label": label, "min": low, "max": high}
            for low, high, code, label in scoring.BANDS
        ],
        "limitations": [
            "An index, not a calibrated probability of default.",
            "Weights are set by policy judgement and documented above, not learned from outcomes.",
            "No outcome-trained model is shipped until the lender's own dispositions accumulate.",
            "Derived from a synthetic portfolio; not validated on any lender's book.",
        ],
        "planned": [
            "P(miss next instalment) trained on twelve months of the lender's own repayment history.",
            "Expected-value prioritisation using measured cost-to-collect per channel.",
            "Uplift / next-best-action once logged dispositions and holdout slices accumulate.",
        ],
    }


# --------------------------------------------------------------------------
# Lead magnet: triage the prospect's own loan tape
# --------------------------------------------------------------------------
TRIAGE_COLUMNS = [
    "borrower_name",
    "product",
    "principal",
    "outstanding",
    "instalment",
    "dpd",
    "arrears",
    "monthly_inflow",
    "inflow_change_pct",
]


@app.get("/api/triage/template", response_class=PlainTextResponse)
def triage_template() -> str:
    buffer = io.StringIO()
    writer = csv.writer(buffer)
    writer.writerow(TRIAGE_COLUMNS)
    writer.writerow(["Adeola Foods Ltd", "WC", "5000000", "3800000", "612000", "0", "0",
                     "3100000", "-34"])
    writer.writerow(["Prime Logistics Nigeria Ltd", "AF", "18000000", "11400000", "742000", "31",
                     "742000", "4200000", "-12"])
    return buffer.getvalue()


@app.post("/api/triage")
async def triage(file: UploadFile = File(...)) -> dict[str, Any]:
    """Score an uploaded loan tape with the same engine, no integration required.

    This is the shortest honest path from "interesting" to "show me on my own data".
    """
    if not file.filename or not file.filename.lower().endswith(".csv"):
        raise HTTPException(status_code=400, detail="Upload a .csv file.")

    raw = await file.read()
    await file.close()
    if not raw.strip():
        raise HTTPException(status_code=400, detail="The uploaded file is empty.")

    try:
        text = raw.decode("utf-8-sig")
    except UnicodeDecodeError:
        text = raw.decode("latin-1")

    reader = csv.DictReader(io.StringIO(text))
    if not reader.fieldnames:
        raise HTTPException(status_code=400, detail="The CSV has no header row.")

    normalised = {name.strip().lower().replace(" ", "_"): name for name in reader.fieldnames}
    required = {"borrower_name", "outstanding", "instalment", "dpd"}
    missing = sorted(required - set(normalised))
    if missing:
        raise HTTPException(
            status_code=400,
            detail=(
                "Missing required column(s): "
                + ", ".join(missing)
                + ". Required: borrower_name, outstanding, instalment, dpd. "
                "Optional: product, principal, arrears, monthly_inflow, inflow_change_pct."
            ),
        )

    def value(row: dict, key: str, default: float = 0.0) -> float:
        column = normalised.get(key)
        if column is None:
            return default
        raw_value = (row.get(column) or "").strip().replace(",", "").replace("\u20a6", "")
        if not raw_value:
            return default
        try:
            return float(raw_value)
        except ValueError:
            return default

    rows: list[dict] = []
    sampled = 0
    for index, row in enumerate(reader):
        if index >= 5000:
            break
        sampled += 1
        name_column = normalised["borrower_name"]
        name = (row.get(name_column) or f"Row {index + 2}").strip()
        dpd = int(max(0, value(row, "dpd")))
        instalment = max(0.0, value(row, "instalment"))
        outstanding = max(0.0, value(row, "outstanding"))
        arrears = value(row, "arrears") or (instalment if dpd > 0 else 0.0)
        inflow = value(row, "monthly_inflow")
        change = value(row, "inflow_change_pct", None) if normalised.get("inflow_change_pct") else None
        product = (row.get(normalised.get("product", ""), "") or "WC").strip().upper()[:3] or "WC"

        account = {
            "dpd": dpd,
            "arrears_amount": arrears,
            "instalment": instalment,
            "monthly_inflow_base": inflow,
            "instalments_paid": 0 if dpd > 0 else 1,
            "band": config.band_for_dpd(dpd),
            "product_code": product,
            "oldest_unpaid_due": "the uploaded tape",
            "short_payments_last_3": 0,
        }
        signals: list[dict] = []
        if change is not None and change <= -10:
            signals.append(
                {
                    "code": "inflow_decline",
                    "label": "Cash inflows falling",
                    "severity": 3 if change < -42 else 2,
                    "detected_at": config.AS_OF.isoformat(),
                    "headline": f"Average monthly inflows fell {abs(change):.0f}%",
                    "evidence": {"change_pct": change},
                    "lead_days": None,
                    "actionable": True,
                }
            )
        cashflow = (
            {
                "change_pct": change,
                "recent_3m_avg": inflow * (1 + (change or 0) / 100) if inflow else None,
                "prior_3m_avg": inflow if inflow else None,
            }
            if inflow or change is not None
            else None
        )

        risk = scoring.score_account(account, signals, cashflow)
        recommendation = playbooks.recommend(account, signals, risk, cashflow)
        value_engine = priority.evaluate(account, risk, recommendation["primary"], outstanding)

        rows.append(
            {
                "borrower_name": name,
                "product": product,
                "dpd": dpd,
                "band": account["band"],
                "band_label": config.BANDS[account["band"]]["label"],
                "outstanding": round(outstanding),
                "instalment": round(instalment),
                "arrears": round(arrears),
                "risk_index": risk["index"],
                "risk_band": risk["band_label"],
                "reasons": risk["reasons"][:3],
                "playbook": recommendation["primary"]["name"],
                "playbook_code": recommendation["primary"]["code"],
                "expected_recovery": value_engine["expected_recovery"],
                "loss_at_risk": value_engine["loss_at_risk"],
                "priority": value_engine["priority"],
                "exposure": round(outstanding),
                # Nested shapes so the ranking helper works identically for an
                # uploaded tape and the seeded book.
                "priority_value": value_engine,
                "risk": risk,
            }
        )

    if not rows:
        raise HTTPException(status_code=400, detail="The CSV contains no data rows.")

    ranking = priority.apply_review_budget(rows, None)
    book = sum(row["outstanding"] for row in rows)
    par30 = [row for row in rows if row["dpd"] >= 1]

    return {
        "accounts": len(rows),
        "book_outstanding": book,
        "par30": {
            "accounts": len(par30),
            "count_pct": round(len(par30) / len(rows) * 100, 1),
            "value_pct": round(
                sum(row["outstanding"] for row in par30) / max(1, book) * 100, 1
            ),
        },
        "expected_recovery_available": ranking["total_expected_recovery"],
        "ranking": ranking,
        "worklist": sorted(
            rows, key=lambda row: row["expected_recovery"], reverse=True
        )[:200],
        "note": (
            "Scored by the Northline Risk Index with the same weights used in the product. "
            "The upload is held in memory for this response only and is not stored."
        ),
    }
